### ISSUE TITLE
Hard coded values in the library

### ISSUE THREAD

**Issue by rohith2506** [brunneis/pygram#2]
Hey,

Thanks for your work on this library. I was wondering about these constants here

https://github.com/labteral/pygram/blob/master/pygram/pygram.py#L119

Can you tell me where did you get them? Are these constants common for everyone? If not, How can I get them for my own crawler?

I am trying to port your library to go and I am kind of stuck here.

Thanks,
Rohith

**Comment by brunneis** [comment]
Hi @rohith2506! They are common for everyone. I got them by inspecting the API calls in the browser. However, they could change (but they don't). Each type of call has a different query hash. You can use the same. If you search the query hashes you will find more people using them (https://www.startpage.com/do/dsearch?query=c76146de99bb02f6415203be841dd25a&cat=web&pl=opensearch)

![image](https://user-images.githubusercontent.com/9011434/84684309-c8cb0880-af38-11ea-8df0-a7b2fb422f86.png)

Cheers!
